server: "hub-cloud.browserstack.com"
user: "akashdutta4"
key: "mRNTo1K9jep2ptxFdo1a"

common_caps:
  "build": "rspec-browserstack"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
  -
    "browser": "firefox"
  -
    "browser": "internet explorer"
  -
    "browser": "safari"
